/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddWineDialog: typeof import('./src/components/wineList/AddWineDialog.vue')['default']
    FilterSection: typeof import('./src/components/FilterSection.vue')['default']
    FloatingConfigurator: typeof import('./src/components/FloatingConfigurator.vue')['default']
    ForgotPasswordDialog: typeof import('./src/components/ForgotPasswordDialog.vue')['default']
    ForgotPasswordForm: typeof import('./src/components/form/ForgotPasswordForm.vue')['default']
    FormPassword: typeof import('./src/components/form/FormPassword.vue')['default']
    FormSelectPrice: typeof import('./src/components/form/FormSelectPrice.vue')['default']
    Lists: typeof import('./src/components/list/Lists.vue')['default']
    ResetPasswordForm: typeof import('./src/components/form/ResetPasswordForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WineDetailsDialog: typeof import('./src/components/wineListItem/WineDetailsDialog.vue')['default']
    WineEditPrice: typeof import('./src/components/wineListItem/WineEditPrice.vue')['default']
  }
}
