/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddWineDialog: typeof import('./src/components/wineList/AddWineDialog.vue')['default']
    AutoComplete: typeof import('primevue/autocomplete')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    CardList: typeof import('./src/components/list/CardList.vue')['default']
    Column: typeof import('primevue/column')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    ConfirmPopup: typeof import('primevue/confirmpopup')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    DialogAge: typeof import('./src/components/DialogAge.vue')['default']
    DialogCreateWineList: typeof import('./src/components/list/DialogCreateWineList.vue')['default']
    DialogEditImageList: typeof import('./src/components/DialogEditImageList.vue')['default']
    DIalogEditImageList: typeof import('./src/components/DIalogEditImageList.vue')['default']
    Drawer: typeof import('primevue/drawer')['default']
    Fieldset: typeof import('primevue/fieldset')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    FilterSection: typeof import('./src/components/FilterSection.vue')['default']
    FloatingConfigurator: typeof import('./src/components/FloatingConfigurator.vue')['default']
    ForgotPasswordDialog: typeof import('./src/components/ForgotPasswordDialog.vue')['default']
    ForgotPasswordForm: typeof import('./src/components/form/ForgotPasswordForm.vue')['default']
    Form: typeof import('@primevue/forms/form')['default']
    FormPassword: typeof import('./src/components/form/FormPassword.vue')['default']
    FormSelectPrice: typeof import('./src/components/form/FormSelectPrice.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Lists: typeof import('./src/components/list/Lists.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Message: typeof import('primevue/message')['default']
    Paginator: typeof import('primevue/paginator')['default']
    Password: typeof import('primevue/password')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    QRCodeGenerator: typeof import('./src/components/QRCodeGenerator.vue')['default']
    ResetPasswordForm: typeof import('./src/components/form/ResetPasswordForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Step: typeof import('primevue/step')['default']
    StepList: typeof import('primevue/steplist')['default']
    StepPanel: typeof import('primevue/steppanel')['default']
    StepPanels: typeof import('primevue/steppanels')['default']
    Stepper: typeof import('primevue/stepper')['default']
    Tag: typeof import('primevue/tag')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleButton: typeof import('primevue/togglebutton')['default']
    WineDetailsDialog: typeof import('./src/components/wineListItem/WineDetailsDialog.vue')['default']
    WineEditPrice: typeof import('./src/components/wineListItem/WineEditPrice.vue')['default']
  }
  export interface ComponentCustomProperties {
    StyleClass: typeof import('primevue/styleclass')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
