version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "5173:80" # Пробрасываем порт 5173 на порт 80 внутри контейнера
    volumes:
      - ./certs:/etc/letsencrypt # Хранение сертификатов
      - ./logs:/var/log/nginx # Логи Nginx
      - ./vue-app/dist:/usr/share/nginx/html # Подключаем директорию с собранным приложением
    environment:
      - DOMAIN=admin.w-list.ru
      - SUBDOMAINS=www.admin.w-list.ru
    restart: always
    depends_on:
      - vue-builder

  vue-builder:
    image: node:latest
    container_name: vue-builder
    working_dir: /usr/src/app
    volumes:
      - ./vue-app:/usr/src/app # Подключаем локальную папку с приложением
    command: sh -c "npm install && npm run build-only" # Устанавливаем зависимости и запускаем сборку приложения
    restart: "no" # Не перезапускаем после завершения сборки
