name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.20
        options: --privileged
        ports:
          - 5173:80  # Expose the port for Nginx service

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and run Docker Compose
        run: |
          # Build and run the Docker Compose services
          docker-compose -f docker-compose.yml up --build --abort-on-container-exit

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Wait for the build job to complete successfully

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          USERNAME: ${{ secrets.USERNAME }}
        run: |
          # Убедитесь, что sshpass установлен
          sudo apt-get update
          sudo apt-get install -y sshpass

          # Копируем файлы на сервер
          sshpass -e scp -o StrictHostKeyChecking=no -r ./path/to/your/build user@${{ secrets.SERVER_IP }}:/path/on/server

          # Выполняем удаленный деплой
          sshpass -e ssh -o StrictHostKeyChecking=no user@${{ secrets.SERVER_IP }} << 'EOF'
            cd /path/on/server
            docker-compose down
            docker-compose up -d --build
          EOF
